### ISSUE TITLE
Examples for web-transport-wasm

### ISSUE THREAD

**Issue by Masterchef365** [kixelated/web-transport-rs#44]
Hi all, I'm attempting to use self-signed certificates on the web platform (wasm32). I tried to use the `server_certificate_hashes()` method on `SessionBuilder` to no avail. Both firefox and chrome complain that the certificate my server is using isn't recognized. I'm able to use web-transport-quinn on native with my self-signed certificates just fine. 

Are there any examples for web-transport-wasm, specifically using self-signed certificates? 
Thanks!

**Comment by kixelated** [comment]
Oh I'm so sorry that I didn't see this message until now.

Check out: https://github.com/kixelated/moq-wasm
